import { StyleSheet, Platform } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { Fonts as FONTS } from '../../assets/theme/fonts';
import { colors } from '../../assets/theme/colours';

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  mapContainer: {
    width: wp('100%'),
    height: hp('40%'),
    position: 'absolute',
    top: 0,
  },
  map: {
    flex: 1,
  },
  reCenterButton: {
    position: 'absolute',
    bottom: hp('2%'),
    right: wp('4%'),
    backgroundColor: colors.white,
    width: wp('11%'),
    height: wp('11%'),
    borderRadius: wp('5.5%'),
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  searchAbsoluteContainer: {
    position: 'absolute',
    top: hp('2%'),
    width: wp('90.7%'),
    alignSelf: 'center',
    zIndex: 9999,
    elevation: 20,
  },
  geocodingBanner: {
    width: wp('90.7%'),
    alignSelf: 'center',
    marginTop: hp('1%'),
    backgroundColor: colors.themeWhite,
    borderRadius: wp('2%'),
    paddingVertical: hp('1%'),
    paddingHorizontal: wp('3%'),
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.themeLightGray,
    elevation: 4,
  },
  geocodingText: {
    marginLeft: wp('2%'),
    color: colors.black,
    fontFamily: FONTS.poppins.regular,
    fontSize: wp('3.2%'),
  },
  detailedAddressContainer: {
    backgroundColor: colors.white,
    flex: 1,
    borderTopLeftRadius: hp('4%'),
    borderTopRightRadius: hp('4%'),
    marginTop: hp('35%'),
    paddingTop: hp('2%'),
    paddingHorizontal: wp('5%'),
  },
  upperDivider: {
    width: wp('20%'),
    height: hp('0.8%'),
    backgroundColor: colors.themeLightGray,
    borderRadius: 10,
    alignSelf: 'center',
    marginBottom: hp('1%'),
  },
  dragInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('1%'),
    alignSelf: 'center',
    //paddingHorizontal: wp('1%'),
  },
  dragInfoText: {
    fontSize: wp('3.1%'),
    color: colors.themeDarkGray,
    fontStyle: 'italic',
    fontFamily: FONTS.poppins.regular,
    marginLeft: wp('1.5%'),
    flex: 1,
  },
  topView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('2.5%'),
  },
  backButtonContainer: {
    padding: wp('1%'),
  },
  addLocationText: {
    fontFamily: FONTS.poppins.semiBold,
    fontSize: wp('4.6%'),
    color: colors.black,
    marginLeft: wp('4%'),
  },
  innerView: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: hp('2.5%'),
  },
  locationIcon: {
    width: wp('6%'),
    height: wp('7.5%'),
    tintColor: colors.themeTeal,
    resizeMode: 'contain',
  },
  fetchingLocation: {
    color: colors.black,
    fontFamily: FONTS.poppins.medium,
    fontSize: wp('4%'),
    marginLeft: wp('3%'),
  },
  addressLineText: {
    color: colors.themeDarkGray,
    fontSize: wp('3.4%'),
    fontFamily: FONTS.poppins.regular,
    marginLeft: wp('3%'),
    marginTop: hp('0.5%'),
  },
  delboyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF5F0',
    padding: wp('3%'),
    borderRadius: 12,
    marginBottom: hp('2.5%'),
  },
  delBoyImage: {
    width: wp('12%'),
    height: wp('12%'),
    resizeMode: 'contain',
  },
  detailedLocationContainer: {
    marginLeft: wp('3%'),
  },
  detailedLocationText: {
    fontSize: wp('3.2%'),
    color: colors.black,
    fontFamily: FONTS.poppins.regular,
  },
  saveAsText: {
    fontFamily: FONTS.poppins.semiBold,
    fontSize: wp('4%'),
    color: colors.black,
    marginBottom: hp('1.5%'),
  },
  addressTypesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp('3%'),
  },
  addressTypeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.themeLightGray,
    borderRadius: 25,
    width: wp('28%'),
    paddingVertical: hp('1.2%'),
  },
  selectedAddressType: {
    backgroundColor: colors.themeTeal,
    borderColor: colors.themeTeal,
  },
  addressTypeIcon: {
    width: wp('4%'),
    height: wp('4%'),
    resizeMode: 'contain',
    marginRight: wp('2%'),
  },
  addressTypeText: {
    fontSize: wp('3.4%'),
    fontFamily: FONTS.poppins.medium,
    color: colors.themeDarkGray,
  },
  selectedTypeText: {
    color: colors.white,
  },
  inputWrapper: {
    marginBottom: hp('2%'),
  },
  label: {
    fontFamily: FONTS.poppins.regular,
    color: colors.themeDarkGray,
    fontSize: wp('3.2%'),
    marginBottom: hp('0.5%'),
  },
  input: {
    borderWidth: 1,
    borderColor: colors.themeLightGray,
    borderRadius: 8,
    paddingHorizontal: wp('4%'),
    height: hp('6%'),
    color: colors.black,
    fontFamily: FONTS.poppins.regular,
    fontSize: wp('3.7%'),
  },
  pincodeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: hp('2%'),
  },
  buttonGradientStyle: {
    borderRadius: 30,
    height: hp('7%'),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp('2%'),
    marginBottom: hp('4%'),
  },
  buttonText: {
    color: colors.white,
    fontFamily: FONTS.poppins.bold,
    fontSize: wp('4%'),
    textTransform: 'uppercase',
  },
});
