import { StyleSheet, Platform } from 'react-native';
import { colors, fontColors } from '../../assets/theme/colours';
import { Fonts } from '../../assets/theme/fonts';
import { hp, wp } from '../../utils/responsive';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerGradient: {
    height: hp('20%'),
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    overflow: 'hidden',
  },
  headerContent: {
    flex: 1,
    // paddingHorizontal: wp('5%'),
    paddingTop: Platform.OS === 'ios' ? hp('1%') : hp('5%'),
  },
  backButton: {
    marginStart: wp('2%'),
  },
  userInfoContainer: {
    width: wp('90%'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: wp('5%'),
    marginTop: hp('1%'),
  },
  userProfileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    marginRight: wp('2%'),
  },
  avatarContainer: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.lightGrey,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  userDetails: {
    flexShrink: 1,
    marginLeft: wp('3%'),
  },
  welcomeText: {
    fontSize: 16,
    fontFamily: Fonts.gilroyMedium,
    color: fontColors.titleBlack,
    marginVertical: hp('0.3%'),
  },
  userName: {
    fontSize: 22,
    fontFamily: Fonts.gilroyBold,
    color: fontColors.titleBlack,
    marginTop: -4,
    fontWeight: 'bold',
  },
  userPhone: {
    fontSize: 12,
    marginVertical: hp('0.3%'),
    fontFamily: Fonts.gilroyRegular,
    color: fontColors.titleBlack,
    opacity: 0.6,
  },
  headerRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
  },
  coinPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#FFAD00',
    marginRight: wp('3%'),
  },
  coinText: {
    fontSize: 16,
    fontFamily: Fonts.gilroyBold,
    color: colors.white,
    marginLeft: 6,
  },
  notificationBell: {
    padding: 5,
  },
  quickActionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp('5%'),
    marginTop: hp('3%'),
  },
  actionCard: {
    width: wp('28%'),
    backgroundColor: colors.white,
    borderRadius: 15,
    paddingVertical: hp('3%'),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: colors.lightGrey,
    // elevation: 5,
    // shadowColor: colors.black,
    // shadowOffset: { width: 0, height: 2 },
    // shadowOpacity: 0.1,
    // shadowRadius: 4,
  },
  actionText: {
    fontSize: 12,
    fontFamily: Fonts.gilroyMedium,
    color: fontColors.titleBlack,
    marginTop: 8,
  },
  referIllustration: {
    width: wp('90%'),
    height: hp('15%'),
    alignSelf: 'center',
    marginTop: hp('2%'),
  },
  sectionContainer: {
    paddingHorizontal: wp('5%'),
    marginTop: hp('3%'),
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: Fonts.gilroyBold,
    color: fontColors.titleBlack,
    marginBottom: hp('1%'),
  },
  menuCard: {
    backgroundColor: colors.white,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: hp('1%'),
    paddingHorizontal: wp('4%'),
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  menuIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuItemText: {
    flex: 1,
    fontSize: 14,
    fontFamily: Fonts.gilroyRegular,
    color: fontColors.titleBlack,
    fontWeight: '300',
    marginLeft: wp('3%'),
    letterSpacing: 0.5,
  },
  badgeContainer: {
    backgroundColor: 'red',
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  badgeText: {
    color: colors.white,
    fontSize: 10,
    fontFamily: Fonts.gilroyBold,
  },
  logoutButton: {
    backgroundColor: colors.logoutred,
    marginHorizontal: wp('30%'),
    marginTop: hp('4%'),
    paddingVertical: hp('1.5%'),
    borderRadius: 25,
    alignItems: 'center',
  },
  logoutText: {
    color: colors.white,
    fontSize: 14,
    fontFamily: Fonts.bold,
    fontWeight: 'bold',
  },
  footerContainer: {
    alignItems: 'center',
    marginTop: hp('3%'),
    marginBottom: hp('5%'),
  },
  footerLogo: {
    width: wp('50%'),
    height: 70,
  },
  backgroundImage: {
    flex: 1,
    alignItems: 'center',
    borderBottomLeftRadius: wp('9.3%'),
    borderBottomRightRadius: wp('9.3%'),
    //  paddingTop: hp('6%'),
    paddingBottom: hp('7.5%'),
    overflow: 'hidden',
  },
  // Edit Profile specific styles
  editProfileContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  editProfileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    //paddingHorizontal: 10,
    marginEnd: 16,
    //paddingTop: Platform.OS === 'ios' ? hp('6%') : hp('6%'),
    paddingBottom: hp('2%'),
    backgroundColor: colors.white,
  },
  editProfileTitle: {
    fontSize: 18,
    fontFamily: Fonts.gilroyBold,
    color: fontColors.titleBlack,
    flex: 1,
    marginLeft: wp('4%'),
  },
  editProfileCartIconBg: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.themeTeal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editProfileFormContainer: {
    paddingHorizontal: wp('5%'),
    marginTop: hp('3%'),
  },
  inputGroup: {
    marginBottom: hp('2.5%'),
  },
  inputLabel: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    color: fontColors.titleBlack,
    fontWeight: '400',
    marginBottom: hp('1%'),
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 25,
    paddingHorizontal: wp('4%'),
    height: hp('6%'),
    backgroundColor: colors.white,
  },
  textInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: Fonts.gilroyMedium,
    color: fontColors.titleBlack,
    height: '100%',
  },
  eyeIconContainer: {
    padding: 5,
  },
});
