import { StyleSheet, Platform } from 'react-native';
import { hp, wp } from '../../utils/responsive';
import { colors, fontColors } from '../../assets/theme/colours';
import { Fonts as FONTS } from '../../assets/theme/fonts';

export const styles = StyleSheet.create({
    mainContainer: { flex: 1, backgroundColor: colors.white },
    backgroundImage: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: hp('6%'),
        paddingBottom: hp('7.5%'),
    },
    kapraLogo: { width: wp('47%'), height: hp('10%'), resizeMode: 'cover' },
    tagLine: { width: wp('50.7%'), height: hp('16.95%'), resizeMode: 'cover' },
    bottomContainer: {
        height: hp('38%'),
        paddingHorizontal: wp('5.8%'),
        paddingTop: hp('3.5%'),
        borderTopLeftRadius: wp('9.3%'),
        borderTopRightRadius: wp('9.3%'),
        backgroundColor: colors.white,
        marginTop: -hp('4%'),
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
    },
    headerText: {
        fontFamily: FONTS.gilroySemiBold,
        fontSize: wp('4.65%'),
        color: fontColors.titleBlack,
        alignSelf: 'center',
        fontWeight: 'bold',
    },
    phoneNoEditContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: hp('1%'),
        alignSelf: 'center',
        marginBottom: hp('3%'),
    },
    phoneNoText: { fontFamily: FONTS.gilroyRegular, fontSize: wp('3.72%'), color: fontColors.titleBlack },
    editIconImage: { width: wp('2.79%'), height: wp('2.79%'), marginLeft: wp('2%') },
    enterNumberText: {
        fontFamily: FONTS.gilroyRegular,
        fontSize: wp('3.72%'),
        color: fontColors.subtext,
        marginBottom: hp('0.5%'),
        alignSelf: 'center',
    },
    otpContainer: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: wp('5%'), marginBottom: hp('2%') },
    numberBox: {
        width: wp('12.95%'),
        height: hp('6.36%'),
        backgroundColor: colors.white,
        borderWidth: 0.5,
        borderColor: colors.themeLightGray,
        borderRadius: wp('6.33%'),
        justifyContent: 'center',
        alignItems: 'center',
    },
    otpInput: { fontSize: wp('4.5%'), textAlign: 'center', width: '100%', color: fontColors.titleBlack },
    pwdResendTimeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: hp('0.8%'),
        paddingHorizontal: wp('5%'),
        marginBottom: hp('4%'),
    },
    usePwdText: { fontFamily: FONTS.gilroyMedium, fontSize: wp('3.25%'), color: colors.themeTeal },
    time: { fontFamily: FONTS.gilroyRegular, fontSize: wp('3.25%'), color: fontColors.subtext },
});
